import type { EngineMode, Side } from '../engine/types'

interface Props { mode: EngineMode; humanSide: Side; thinkTime: number; stockfishElo: number; stockfishThinkTime: number; stockfishSide: Side; running: boolean; showBestMove: boolean; onMode: (value: EngineMode) => void; onSide: (value: Side) => void; onTime: (value: number) => void; onStockfishElo: (value: number) => void; onStockfishTime: (value: number) => void; onStockfishSide: (value: Side) => void; onToggle: () => void; onFlip: () => void; onShowBestMove: (value: boolean) => void; onReset: () => void; onFen: () => void; onPgn: () => void; onExport: () => void }

const MIN_THINK_TIME_MS = 100
const MAX_THINK_TIME_MS = 10_000
const THINK_TIME_STEP_MS = 100

function formatThinkTime(ms: number) {
  return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms} ms`
}

export function SettingsPanel(props: Props) {
  const usesStockfish = props.mode === 'human-stockfish' || props.mode === 'mojo-stockfish'
  const engineGame = props.mode === 'engine-engine' || props.mode === 'mojo-stockfish'
  return <div className="settings-panel"><label>Mode<select value={props.mode} onChange={(event) => props.onMode(event.target.value as EngineMode)}><option value="human-engine">You vs Mojo</option><option value="human-stockfish">You vs Stockfish</option><option value="engine-engine">Mojo vs Mojo</option><option value="mojo-stockfish">Mojo vs Stockfish</option><option value="human-human">You vs You</option></select></label>{(props.mode === 'human-engine' || props.mode === 'human-stockfish') && <label>Your color<select value={props.humanSide} onChange={(event) => props.onSide(event.target.value as Side)}><option value="white">White</option><option value="black">Black</option></select></label>}{props.mode === 'mojo-stockfish' && <label>Stockfish color<select value={props.stockfishSide} onChange={(event) => props.onStockfishSide(event.target.value as Side)}><option value="white">White</option><option value="black">Black</option></select></label>}<label>Mojo time · {formatThinkTime(props.thinkTime)}<input type="range" min={MIN_THINK_TIME_MS} max={MAX_THINK_TIME_MS} step={THINK_TIME_STEP_MS} value={props.thinkTime} onChange={(event) => props.onTime(Number(event.target.value))} /></label>{usesStockfish && <div className="stockfish-settings"><label>Stockfish target Elo · {props.stockfishElo}<input type="range" min={1320} max={3190} step={10} value={props.stockfishElo} onChange={(event) => props.onStockfishElo(Number(event.target.value))} /></label><label>Stockfish time · {formatThinkTime(props.stockfishThinkTime)}<input type="range" min={MIN_THINK_TIME_MS} max={MAX_THINK_TIME_MS} step={THINK_TIME_STEP_MS} value={props.stockfishThinkTime} onChange={(event) => props.onStockfishTime(Number(event.target.value))} /></label><p className="setting-note">Target Elo is an approximate Stockfish calibration.</p></div>}<label className="toggle-control"><input type="checkbox" checked={props.showBestMove} onChange={(event) => props.onShowBestMove(event.target.checked)} /><span>Show best-move arrow</span></label><div className="control-grid">{engineGame && <button type="button" className="primary" onClick={props.onToggle}>{props.running ? 'Pause game' : 'Start game'}</button>}<button type="button" onClick={props.onFlip}>Flip board</button><button type="button" onClick={props.onFen}>Load FEN</button><button type="button" onClick={props.onPgn}>Load PGN</button><button type="button" onClick={props.onExport}>Export PGN</button><button type="button" className="reset-game" onClick={props.onReset}>Reset game</button></div></div>
}
